services:
  registry:
    image: registry:2.8.3
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry:/data

volumes:
  registry:
